FROM python:3.7-alpine
MAINTAINER yasmine
RUN apk add --no-cache gcc musl-dev linux-headers

WORKDIR /code  

ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .  
CMD ["flask", "run"]  # Correction ici
EXPOSE 5000
