version: '2'

services:
  php:
    build:
      context: .
      dockerfile: dockerfile
    container_name: php73
    image: php:7.3.2-apache
    volumes:
      - ./php:/var/www/html
    ports:
      - 80:80
  db:
    container_name: mysql18
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: tpreseau
      MYSQL_DATABASE: virtualization
      MYSQL_USER: tpreseau
      MYSQL_PASSWORD: monpassword
    ports:
      - 3306:3306
  phpmya:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: tpreseau
      PMA_PASSWORD: monpassword
      UPLOAD_LIMIT: 20M
    ports:
      - 8899:80